apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    spec:
      containers:
        - name: hello
          image: busybox
          command:
          - /bin/sh
          - -c
          - date; echo Hello
      restartPolicy: Never
  backoffLimit: 4