apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: test-2
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: mypod
          image: yaroslavperf/gb-k8s-lecture-2:1.0