apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: test-2
  labels:
    app: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80