kind: Service
apiVersion: v1
metadata:
  name: prometheus-operator-kube-p-prometheus
  namespace: test-2
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 16.15.0
    chart: kube-prometheus-stack-16.15.0
    heritage: Helm
    prometheus: prometheus-operator-kube-p-prometheus
    release: prometheus-operator
    self-monitor: 'true'
  annotations:
    meta.helm.sh/release-name: prometheus-operator
    meta.helm.sh/release-namespace: prometheus
spec:
  ports:
    - name: web
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090
  selector:
    prometheus: prometheus-operator-kube-p-prometheus
  type: NodePort