apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myservicemonitor
  namespace: test-2
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  endpoints:
  - port: http
    interval: 1m
    path: /metrics